routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Client')->group(function () {
	Route::get('/', 'SiteController@home')->name('home');

	Route::get(
		'bautizo',
		'SiteController@christening'
	)->name('christening')->middleware('auth');

	Route::get(
		'view-cv',
		'CurriculumVitaeController@viewCurriculumVitae'
	)->name('view-cv');
	Route::get(
		'download-cv',
		'CurriculumVitaeController@downloadCurriculumVitae'
	)->name('download-cv');
	Route::get(
		'curriculum-vitae-carlos-amores',
		'CurriculumVitaeController@index'
	)->name('curriculum');

	Route::get('curriculum-{name}', function ($name) {
		return redirect(route('curriculum'), 301);
	})->where('name', '[A-Za-z]+');

	// Blog
	Route::group(['prefix' => 'blog'], function () {
		Route::get(
			'/',
			'MiniblogController@home'
		)->name('blog');
		// Route::get(
		//     '/{category}',
		//     'MiniblogController@category'
		// )->name('blog.category');
		Route::get(
			'/{title}',
			'MiniblogController@post'
		)->name('blog.post');
	});
});

// Authentication
Auth::routes();

Route::namespace('Admin')->group(function () {
	Route::prefix('admin')->group(function () {
		Route::group(['middleware' => 'auth'], function () {
			Route::get('/', 'AdminController@home')->name('cms-home');

			Route::resource('/encryption', 'EncryptionController');

			// CRUD with Vuejs
			Route::get('articles', function () {
				return view('back.article.index');
			})->name('articles.index');
			// List articles
			Route::get('article', 'ArticleController@index');
			// List single article
			Route::get('article/{id}', 'ArticleController@show');
			// Create new article
			Route::post('article', 'ArticleController@store');
			// Update article
			Route::put('article', 'ArticleController@store');
			// Delete article
			Route::delete('article/{id}', 'ArticleController@destroy');

			// Crud with MongoDB
			Route::resource('/car', 'CarController');

			// Edit and update user profile
			// Route::resource(
			//     '/user',
			//     'UserController',
			//     ['only' => ['edit', 'update']]
			// );
			Route::get(
				'/user/{user}/edit',
				'UserController@edit'
			)->name('user-edit');
			Route::put(
				'/user/{user}',
				'UserController@update'
			)->name('user-update');

			// Invoices Carlos Cueva
			Route::resource('/invoice', 'InvoiceController');
			Route::get(
				'/download-all-invoices-{month}',
				'InvoiceController@downloadAllInvoice'
			)->name('download-all-invoices');
			Route::post(
				'/sent-all-invoices-{month}',
				'InvoiceController@sentAllInvoice'
			)->name('sent-all-invoices');
			Route::get(
				'/invoice-pdf-{cif}-{year}-{month}/{number?}',
				'InvoiceController@downloadInvoice'
			)->name('download-invoice');
			Route::get(
				'/invoice-{cif}-{year}-{month}/{number?}',
				'InvoiceController@showInvoice'
			)->name('show-invoice');

			Route::group(['middleware' => 'superadmin'], function () {
				Route::resource('/work', 'WorkController');
				Route::resource('/skill', 'SkillController');
				Route::resource('/miniskill', 'MiniskillController');
			});
		});
	});
});

// Routes to SuperAdmin
Route::group(
	[
		'prefix' => 'super-admin',
		'namespace' => 'Admin',
		'middleware' => ['auth', 'superadmin'],
	],
	function () {
		Route::get('/', 'SuperAdminController@home')->name('super.admin.home');
		Route::resource(
			'/user',
			'UserController'
		);
		Route::resource('/notice', 'NoticeController');
		Route::resource('/amazon-product', 'AmazonProductController');
		Route::resource('/post', 'PostController');
		Route::get(
			'/houses/simulation',
			'HouseController@simulation'
		)->name('simulation');
		Route::resource('/houses', 'HouseController');
	}
);

app/Models/Car.php
<?php

namespace Carlos\Amores\Models;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Car extends Eloquent
{
	protected $connection = 'mongodb';
	protected $collection = 'cars';

	protected $fillable = [
		'company', 'model', 'status', 'slug', 'description', 'created_at', 'updated_at',
	];

	public function scopeSearchItem($query, $search)
	{
		$query->where('company', 'like', '%' . $search . '%');
	}
}

app/Http/Controllers/Admin/CarController.php
<?php

namespace Carlos\Amores\Http\Controllers\Admin;

use Carlos\Amores\Models\Car;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Carlos\Amores\Http\Controllers\Controller;

class CarController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index(Request $request)
	{
		// Uso de scopes
		// https://www.youtube.com/watch?v=lsFXi1ILD2Y
		$cars = Car::searchitem($request->get('search'))->get();
		if (empty($request->get('search'))) {
			$cars = Car::all();
		}
		$develop = false;

		return view('admin.car.index', compact('cars', 'develop'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('admin.car.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$car = new Car();
		$car->company = $request->get('company');
		$car->model = $request->get('model');
		$car->status = $request->get('status');
		$car->slug = Str::slug($request->get('company') . '-' . $request->get('model'));
		$car->description = $request->get('description');
		$car->save();

		return redirect()->route('car.index')
			->with('success', 'Car has been successfully added');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param \Carlos\Amores\Models\Car $car
	 *
	 * @return \Illuminate\Http\Response
	 *
	 * @SuppressWarnings(PHPMD.UnusedFormalParameter)
	 */
	public function show(Car $car)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param \Carlos\Amores\Models\Car $car
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit(Car $car)
	{
		return view('admin.car.edit', compact('car'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param \Illuminate\Http\Request  $request
	 * @param \Carlos\Amores\Models\Car $car
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, Car $car)
	{
		$car->company = $request->get('company');
		$car->model = $request->get('model');
		$car->status = $request->get('status');
		$car->slug = Str::slug($request->get('company') . '-' . $request->get('model'));
		$car->description = $request->get('description');
		$car->save();

		return redirect()->route('car.index')
			->with('success', 'Car has been successfully update');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param \Carlos\Amores\Models\Car $car
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(Car $car)
	{
		$car->delete();

		return redirect()->route('car.index')
			->with('success', 'Car has been  deleted');
	}
}

resources/views/admin/car/create.blade.php
@extends('templates.admin.layout')

@section('head')
	<title>Create car</title>
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/jquery-minicolors/jquery.minicolors.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <link href="{{ asset('cms/dist/css/style.min.css') }}" rel="stylesheet">
@endsection


@section('content')
	<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form method="POST" class="form-horizontal" action="{{ route('car.store') }}"
                    enctype="multipart/form-data">
                        @csrf
                        @method('POST')
                        <div class="card-body">
                            <h2 class="card-title">New car</h2>
                            <div class="form-group row">
                                <label for="email1"
                                class="col-sm-3 text-right control-label col-form-label">Company</label>
                                <div class="col-sm-9">
                                    <input type="text" name='company' class="form-control" id="email1" placeholder="Company name" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="fname"
                                class="col-sm-3 text-right control-label col-form-label">Model</label>
                                <div class="col-sm-9">
                                    <input type="text" name="model" class="form-control" id="fname" placeholder="Job" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-3 text-right control-label col-form-label">Status</label>
                                <div class="col-sm-9">
                                    <div class="custom-control custom-radio">
                                        <input type="radio" class="form-control custom-control-input" id="customControlValidation1" name="status" value="1" required>
                                        <label class="custom-control-label" for="customControlValidation1">Active</label>
                                    </div>
                                     <div class="custom-control custom-radio">
                                        <input type="radio" class="form-control custom-control-input" id="customControlValidation2" name="status" value="0" required>
                                        <label class="custom-control-label" for="customControlValidation2">Inactive</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <textarea name="description" class="form-control ckeditor" id="editor1"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="border-top">
                            <div class="card-body">
                                <a href="{{ route('car.index') }}" type="submit" class="btn btn-danger">Cancel</a>
                                <button type="submit" class="btn btn-primary">Store car</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('script')
    <script src="{{ asset('cms/ckeditor/ckeditor.js') }}"></script>
	<script src="{{ asset('cms/assets/libs/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/extra-libs/sparkline/sparkline.js') }}"></script>
    <script src="{{ asset('cms/dist/js/waves.js') }}"></script>
    <script src="{{ asset('cms/dist/js/sidebarmenu.js') }}"></script>
    <script src="{{ asset('cms/dist/js/custom.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>
    <script src="{{ asset('cms/dist/js/pages/mask/mask.init.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/select2/dist/js/select2.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asColor/dist/jquery-asColor.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asGradient/dist/jquery-asGradient.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asColorPicker/dist/jquery-asColorPicker.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-minicolors/jquery.minicolors.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        //***********************************//
        // For select 2
        //***********************************//
        $(".select2").select2();

        /*colorpicker*/
        $('.demo').each(function() {
        //
        // Dear reader, it's actually very easy to initialize MiniColors. For example:
        //
        //  $(selector).minicolors();
        //
        // The way I've done it below is just for the demo, so don't get confused
        // by it. Also, data- attributes aren't supported at this time...they're
        // only used for this demo.
        //
        $(this).minicolors({
                control: $(this).attr('data-control') || 'hue',
                position: $(this).attr('data-position') || 'bottom left',

                change: function(value, opacity) {
                    if (!value) return;
                    if (opacity) value += ', ' + opacity;
                    if (typeof console === 'object') {
                        console.log(value);
                    }
                },
                theme: 'bootstrap'
            });

        });
        /*datwpicker*/
        jQuery('.mydatepicker').datepicker();
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });

    </script>
@endsection

resources/views/admin/car/edit.blade.php
@extends('templates.admin.layout')

@section('head')
	<title>Edit car</title>
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/jquery-minicolors/jquery.minicolors.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <link href="{{ asset('cms/dist/css/style.min.css') }}" rel="stylesheet">
@endsection


@section('content')
	<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form method="POST" class="form-horizontal"
                    action="{{ route('car.update',$car) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            <h2 class="card-title">New car</h2>
                            <div class="form-group row">
                                <label for="email1"
                                class="col-sm-3 text-right control-label col-form-label">Company</label>
                                <div class="col-sm-9">
                                    <input type="text" name='company' class="form-control"
                                    id="email1" placeholder="Company name" value="{{ $car->company }}"
                                    required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="fname"
                                class="col-sm-3 text-right control-label col-form-label">Model</label>
                                <div class="col-sm-9">
                                    <input type="text" name="model" class="form-control" id="fname"
                                    placeholder="Job" value="{{ $car->model }}" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-3 text-right control-label col-form-label">Status</label>
                                <div class="col-sm-9">
                                    <div class="custom-control custom-radio">
                                        <input type="radio" class="form-control custom-control-input"
                                        id="customControlValidation1" name="status" value="1" @if ($car->status === "1") checked  @endif required>
                                        <label class="custom-control-label" for="customControlValidation1">Active</label>
                                    </div>
                                    <div class="custom-control custom-radio">
                                        <input type="radio" class="form-control custom-control-input"
                                        id="customControlValidation2" name="status" value="0" @if ($car->status === "0") checked  @endif required>
                                        <label class="custom-control-label" for="customControlValidation2">Inactive</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <textarea name="description" class="form-control ckeditor" id="editor1">{!! $car->description !!}</textarea>
                                </div>
                            </div>
                        </div>
                        <div class="border-top">
                            <div class="card-body">
                                <a href="{{ route('car.index') }}" type="submit" class="btn btn-danger">Cancel</a>
                                <button type="submit" class="btn btn-primary">Update car</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('script')
    <script src="{{ asset('cms/ckeditor/ckeditor.js') }}"></script>
	<script src="{{ asset('cms/assets/libs/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/extra-libs/sparkline/sparkline.js') }}"></script>
    <script src="{{ asset('cms/dist/js/waves.js') }}"></script>
    <script src="{{ asset('cms/dist/js/sidebarmenu.js') }}"></script>
    <script src="{{ asset('cms/dist/js/custom.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>
    <script src="{{ asset('cms/dist/js/pages/mask/mask.init.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/select2/dist/js/select2.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asColor/dist/jquery-asColor.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asGradient/dist/jquery-asGradient.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asColorPicker/dist/jquery-asColorPicker.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-minicolors/jquery.minicolors.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        //***********************************//
        // For select 2
        //***********************************//
        $(".select2").select2();

        /*colorpicker*/
        $('.demo').each(function() {
        //
        // Dear reader, it's actually very easy to initialize MiniColors. For example:
        //
        //  $(selector).minicolors();
        //
        // The way I've done it below is just for the demo, so don't get confused
        // by it. Also, data- attributes aren't supported at this time...they're
        // only used for this demo.
        //
        $(this).minicolors({
                control: $(this).attr('data-control') || 'hue',
                position: $(this).attr('data-position') || 'bottom left',

                change: function(value, opacity) {
                    if (!value) return;
                    if (opacity) value += ', ' + opacity;
                    if (typeof console === 'object') {
                        console.log(value);
                    }
                },
                theme: 'bootstrap'
            });

        });
        /*datwpicker*/
        jQuery('.mydatepicker').datepicker();
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });

    </script>
@endsection

resources/views/admin/car/index.blade.php
@extends('templates.admin.layout')

@section('head')
	<title>Cars</title>
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/extra-libs/multicheck/multicheck.css') }}">
    <link href="{{ asset('cms/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.css') }}" rel="stylesheet">
    <link href="{{ asset('cms/dist/css/style.min.css') }}" rel="stylesheet">
@endsection


@section('content')
	<div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <br>
                        <form class="form-inline" action="{{ route('car.index') }}">
                            <input type="text" class="form-control mb-2 mr-sm-2" name="search">
                            <button type="submit" class="btn btn-primary mb-2">Search</button>
                        </form> <a href="{{ route('car.create') }}"
                            type="submit" class="btn btn-info">Create item</a>
                        <br>
                        <h2 class="card-title">All cars, crud with MongoDB</h2>
                        <div class="table-responsive">
                            <table id="car_datatble" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Company</th>
                                        <th>Model</th>
                                        <th>Status</th>
                                        <th>Description</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                	@foreach ($cars as $w)
	                                    <tr>
	                                        <td>{{ $w->id }}</td>
	                                        <td>{{ $w->company }}</td>
	                                        <td>{{ $w->model }}</td>
	                                        <td>
                                                @if($w->status == 1)
                                                    <span class="badge badge-pill badge-primary">Active</span>
                                                @else
                                                    <span class="badge badge-pill badge-warning">Inactive</span>
                                                @endif
                                            </td>
	                                        <td>{!! $w->description !!}</td>
	                                        <td>
                                                <a class="btn btn-success"
                                                    href="{{ route('car.edit', ['car' => $w->id]) }}">Edit</a>
	                                        	<form method="POST" onclick="return confirm('Do you want delete this item? Are you sure?')" action="{{ route('car.destroy', ['car' => $w->id]) }}">
													@csrf
													@method('DELETE')
	                                        		<button type="submit" class="btn btn-danger">Delete</button>
	                                        	</form>
	                                        </td>
	                                    </tr>
                                	@endforeach
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Id</th>
                                        <th>Company</th>
                                        <th>Model</th>
                                        <th>Status</th>
                                        <th>Description</th>
                                        <th>Actions</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection


@section('script')
	<script src="{{ asset('cms/assets/libs/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/extra-libs/sparkline/sparkline.js') }}"></script>
    <script src="{{ asset('cms/dist/js/waves.js') }}"></script>
    <script src="{{ asset('cms/dist/js/sidebarmenu.js') }}"></script>
    <script src="{{ asset('cms/dist/js/custom.min.js') }}"></script>
    <script src="{{ asset('cms/assets/extra-libs/multicheck/datatable-checkbox-init.js') }}"></script>
    <script src="{{ asset('cms/assets/extra-libs/multicheck/jquery.multicheck.js') }}"></script>
    <script src="{{ asset('cms/assets/extra-libs/DataTables/datatables.min.js') }}"></script>
    <script>
        $('#car_datatble').DataTable();
    </script>
@endsection