routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Client')->group(function () {
	Route::get('/', 'SiteController@home')->name('home');

	Route::get(
		'bautizo',
		'SiteController@christening'
	)->name('christening')->middleware('auth');

	Route::get(
		'view-cv',
		'CurriculumVitaeController@viewCurriculumVitae'
	)->name('view-cv');
	Route::get(
		'download-cv',
		'CurriculumVitaeController@downloadCurriculumVitae'
	)->name('download-cv');
	Route::get(
		'curriculum-vitae-carlos-amores',
		'CurriculumVitaeController@index'
	)->name('curriculum');

	Route::get('curriculum-{name}', function ($name) {
		return redirect(route('curriculum'), 301);
	})->where('name', '[A-Za-z]+');

	// Blog
	Route::group(['prefix' => 'blog'], function () {
		Route::get(
			'/',
			'MiniblogController@home'
		)->name('blog');
		// Route::get(
		//     '/{category}',
		//     'MiniblogController@category'
		// )->name('blog.category');
		Route::get(
			'/{title}',
			'MiniblogController@post'
		)->name('blog.post');
	});
});

// Authentication
Auth::routes();

Route::namespace('Admin')->group(function () {
	Route::prefix('admin')->group(function () {
		Route::group(['middleware' => 'auth'], function () {
			Route::get('/', 'AdminController@home')->name('cms-home');

			Route::resource('/encryption', 'EncryptionController');

			// CRUD with Vuejs
			Route::get('articles', function () {
				return view('back.article.index');
			})->name('articles.index');
			// List articles
			Route::get('article', 'ArticleController@index');
			// List single article
			Route::get('article/{id}', 'ArticleController@show');
			// Create new article
			Route::post('article', 'ArticleController@store');
			// Update article
			Route::put('article', 'ArticleController@store');
			// Delete article
			Route::delete('article/{id}', 'ArticleController@destroy');

			// Crud with MongoDB
			Route::resource('/car', 'CarController');

			// Edit and update user profile
			// Route::resource(
			//     '/user',
			//     'UserController',
			//     ['only' => ['edit', 'update']]
			// );
			Route::get(
				'/user/{user}/edit',
				'UserController@edit'
			)->name('user-edit');
			Route::put(
				'/user/{user}',
				'UserController@update'
			)->name('user-update');

			// Invoices Carlos Cueva
			Route::resource('/invoice', 'InvoiceController');
			Route::get(
				'/download-all-invoices-{month}',
				'InvoiceController@downloadAllInvoice'
			)->name('download-all-invoices');
			Route::post(
				'/sent-all-invoices-{month}',
				'InvoiceController@sentAllInvoice'
			)->name('sent-all-invoices');
			Route::get(
				'/invoice-pdf-{cif}-{year}-{month}/{number?}',
				'InvoiceController@downloadInvoice'
			)->name('download-invoice');
			Route::get(
				'/invoice-{cif}-{year}-{month}/{number?}',
				'InvoiceController@showInvoice'
			)->name('show-invoice');

			Route::group(['middleware' => 'superadmin'], function () {
				Route::resource('/work', 'WorkController');
				Route::resource('/skill', 'SkillController');
				Route::resource('/miniskill', 'MiniskillController');
			});
		});
	});
});

// Routes to SuperAdmin
Route::group(
	[
		'prefix' => 'super-admin',
		'namespace' => 'Admin',
		'middleware' => ['auth', 'superadmin'],
	],
	function () {
		Route::get('/', 'SuperAdminController@home')->name('super.admin.home');
		Route::resource(
			'/user',
			'UserController'
		);
		Route::resource('/notice', 'NoticeController');
		Route::resource('/amazon-product', 'AmazonProductController');
		Route::resource('/post', 'PostController');
		Route::get(
			'/houses/simulation',
			'HouseController@simulation'
		)->name('simulation');
		Route::resource('/houses', 'HouseController');
	}
);

app/Models/Work.php
<?php

namespace Carlos\Amores\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Work extends Model
{
	use SoftDeletes;

	protected $fillable = [
		'company',
		'slug',
		'job',
		'status',
		'description',
		'image',
		'start_date',
		'end_date',
	];

	protected $casts = [
		'status' => 'boolean',
	];

	/**
	 * Scope a query to only include active users.
	 *
	 * @param \Illuminate\Database\Eloquent\Builder $query
	 *
	 * @return \Illuminate\Database\Eloquent\Builder
	 */
	public function scopeActiveWork($query)
	{
		return $query->where('status', true);
	}
}

app/Http/Controllers/Admin/WorkController.php
<?php

namespace Carlos\Amores\Http\Controllers\Admin;

use Carlos\Amores\Events\WorkSavedEvent;
use Carlos\Amores\Http\Controllers\Controller;
use Carlos\Amores\Lib\Constants\HttpStatusCodes;
use Carlos\Amores\Models\Work;
use Carlos\Amores\Repositories\WorkRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;
use Str;

class WorkController extends Controller
{
	// php artisan make:controller WorkController --resource
	// Route::resource('work', 'WorkController');

	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index(WorkRepository $work)
	{
		$works = $work->getWorks();
		//$works = Work::orderBy('start_date', 'ASC')->get();
		return view('admin.work.index', compact('works'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('admin.work.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 *
	 *  @SuppressWarnings(PHPMD.ElseExpression)
	 */
	public function store(Request $request)
	{
		$slug = Str::slug($request->company);
		$request['slug'] = $slug;
		$pathImage = $this->storeImgForWork($request, $slug);
		if (!empty($pathImage)) {
			$request['image'] = $pathImage;
		}
		$work = Work::create($request->all());
		WorkSavedEvent::dispatch($work);
		if (env('CACHE_DRIVER') === 'redis') {
			Cache::tags('works')->flush();
		} else {
			Cache::forget('works.all');
		}
		//Cache::flush();
		return redirect()->route('work.index')->with('success', 'Work created successfully');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Http\Response
	 *
	 * @SuppressWarnings(PHPMD.UnusedFormalParameter)
	 */
	public function show($id)
	{
		return abort(HttpStatusCodes::NOT_FOUND);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$work = Work::where('id', $id)->firstOrFail();

		return view('admin.work.edit', compact('work'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @param int                      $id
	 *
	 * @return \Illuminate\Http\Response
	 *
	 *  @SuppressWarnings(PHPMD.ElseExpression)
	 */
	public function update(Request $request, $id)
	{
		$work = Work::where('id', $id)->firstOrFail();
		$work->company = $request->company;
		$work->job = $request->job;
		$slug = Str::slug($request->company);
		$work->slug = $slug;
		$work->status = $request->status;
		$work->description = $request->description;
		$work->start_date = $request->start_date;
		$work->end_date = $request->end_date;
		$pathImage = $this->storeImgForWork($request, $slug);
		if (!empty($pathImage)) {
			Storage::delete(
				str_replace('storage', 'public', $work->image)
			);
			$work->image = $pathImage;
		}
		$work->save();
		WorkSavedEvent::dispatch($work);
		if (env('CACHE_DRIVER') === 'redis') {
			Cache::tags('works')->flush();
		} else {
			Cache::forget('works.all');
		}
		//Cache::flush();
		return redirect()->route('work.index')->with('primary', 'Work updated correctly');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Http\Response
	 *
	 *  @SuppressWarnings(PHPMD.ElseExpression)
	 */
	public function destroy($id)
	{
		$work = Work::where('id', $id)->firstOrFail();
		Storage::delete(
			str_replace('storage', 'public', $work->image)
		);
		$work->image = null;
		$work->status = false;
		$work->save();
		$work->delete();
		if (env('CACHE_DRIVER') === 'redis') {
			Cache::tags('works')->flush();
		} else {
			Cache::forget('works.all');
		}
		//Cache::flush();
		return redirect()->route('work.index')->with('dark', 'Work deleted successfully');
	}

	/**
	 * Store images for works.
	 *
	 * @param Request $request
	 * @param string  $slug
	 *
	 * @return string|null
	 */
	private function storeImgForWork(Request $request, string $slug): ?string
	{
		if (empty($request->file)) {
			return null;
		}

		try {
			$path = Storage::putFileAs(
				'public/images/works',
				$request->file,
				$slug . '.jpg'
			);
		} catch (\Throwable $th) {
			//throw $th;
			return null;
		}

		return str_replace('public', 'storage', $path);
	}
}

app/Http/Controllers/Api/Curriculum/WorkController.php
<?php

namespace Carlos\Amores\Http\Controllers\Api\Curriculum;

use Carlos\Amores\Http\Controllers\ApiController;
use Carlos\Amores\Lib\Constants\HttpStatusCodes;
use Carlos\Amores\Models\Work;
use Carlos\Amores\Repositories\WorkRepository;

class WorkController extends ApiController
{
	private $workRepository;

	public function __construct(
		WorkRepository $workRepository
	) {
		$this->workRepository = $workRepository;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		return $this->showAll(
			$this->workRepository->getActiveWorks(),
			HttpStatusCodes::OK
		);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param \Carlos\Amores\Models\Work $work
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show(Work $work)
	{
		return $this->showOne($work, HttpStatusCodes::OK);
	}
}

resources/views/admin/work/create.blade.php
@extends('templates.admin.layout')

@section('head')
	<title>Create work</title>
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/jquery-minicolors/jquery.minicolors.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <link href="{{ asset('cms/dist/css/style.min.css') }}" rel="stylesheet">
@endsection


@section('content')
	<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form method="POST" class="form-horizontal" action="{{ route('work.store') }}" enctype="multipart/form-data">
                        @csrf
                        @method('POST')
                        <div class="card-body">
                            <h2 class="card-title">New work</h2>
                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Company</label>
                                <div class="col-sm-9">
                                    <input type="text" name='company' class="form-control" id="email1" placeholder="Company name" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Job</label>
                                <div class="col-sm-9">
                                    <input type="text" name="job" class="form-control" id="fname" placeholder="Job" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-3 text-right control-label col-form-label">Status</label>
                                <div class="col-sm-9">
                                    <div class="custom-control custom-radio">
                                        <input type="radio" class="form-control custom-control-input" id="customControlValidation1" name="status" value="1" required>
                                        <label class="custom-control-label" for="customControlValidation1">Active</label>
                                    </div>
                                     <div class="custom-control custom-radio">
                                        <input type="radio" class="form-control custom-control-input" id="customControlValidation2" name="status" value="0" required>
                                        <label class="custom-control-label" for="customControlValidation2">Inactive</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 text-right control-label col-form-label">File Upload</label>
                                <div class="col-md-9">
                                    <div class="custom-file">
                                        <input type="file" name="file" class="custom-file-input" id="validatedCustomFile">
                                        <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
                                        <div class="invalid-feedback">Example invalid custom file feedback</div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <textarea name="description" class="form-control ckeditor" id="editor1"></textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-3 text-right control-label col-form-label">Start date</label>
                                <div class="input-group col-sm-9">
                                    <input type="text" name="start_date" class="form-control mydatepicker" placeholder="yyyy-mm-dd 00:00:00">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 text-right control-label col-form-label">End date</label>
                                <div class="input-group col-sm-9">
                                    <input type="text" name="end_date" class="form-control" id="datepicker-autoclose" placeholder="yyyy-mm-dd 00:00:00">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                                    </div>
                                </div>
                            </div>


                            {{-- <div class="form-group row">
                                <label class="col-sm-3 text-right control-label col-form-label">Test date</label>
                                <div class="input-group col-sm-9">
                                    <input type="date" name="test_date" class="form-control" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                                    </div>
                                </div>
                            </div> --}}


                        </div>
                        <div class="border-top">
                            <div class="card-body">
                                <a href="{{ route('work.index') }}" type="submit" class="btn btn-danger">Cancel</a>
                                <button type="submit" class="btn btn-primary">Store work</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('script')
    <script src="{{ asset('cms/ckeditor/ckeditor.js') }}"></script>
	<script src="{{ asset('cms/assets/libs/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/extra-libs/sparkline/sparkline.js') }}"></script>
    <script src="{{ asset('cms/dist/js/waves.js') }}"></script>
    <script src="{{ asset('cms/dist/js/sidebarmenu.js') }}"></script>
    <script src="{{ asset('cms/dist/js/custom.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>
    <script src="{{ asset('cms/dist/js/pages/mask/mask.init.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/select2/dist/js/select2.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asColor/dist/jquery-asColor.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asGradient/dist/jquery-asGradient.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asColorPicker/dist/jquery-asColorPicker.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-minicolors/jquery.minicolors.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        //***********************************//
        // For select 2
        //***********************************//
        $(".select2").select2();

        /*colorpicker*/
        $('.demo').each(function() {
        //
        // Dear reader, it's actually very easy to initialize MiniColors. For example:
        //
        //  $(selector).minicolors();
        //
        // The way I've done it below is just for the demo, so don't get confused
        // by it. Also, data- attributes aren't supported at this time...they're
        // only used for this demo.
        //
        $(this).minicolors({
                control: $(this).attr('data-control') || 'hue',
                position: $(this).attr('data-position') || 'bottom left',

                change: function(value, opacity) {
                    if (!value) return;
                    if (opacity) value += ', ' + opacity;
                    if (typeof console === 'object') {
                        console.log(value);
                    }
                },
                theme: 'bootstrap'
            });

        });
        /*datwpicker*/
        jQuery('.mydatepicker').datepicker();
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });

    </script>
@endsection

resources/views/admin/work/edit.blade.php
@extends('templates.admin.layout')

@section('head')
	<title>Edit work</title>
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/jquery-minicolors/jquery.minicolors.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <link href="{{ asset('cms/dist/css/style.min.css') }}" rel="stylesheet">
@endsection


@section('content')
	<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form method="POST" class="form-horizontal" action="{{ route('work.update', [ 'work' => $work->id]) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            <h2 class="card-title">Edit work</h2>
                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Company</label>
                                <div class="col-sm-9">
                                    <input type="text" name='company' class="form-control" id="email1" placeholder="Company name" value="{{ $work->company }}" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Job</label>
                                <div class="col-sm-9">
                                    <input type="text" name="job" class="form-control" id="fname" placeholder="Job" value="{{ $work->job }}" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-3 text-right control-label col-form-label">Status</label>
                                <div class="col-sm-9">
                                    <div class="custom-control custom-radio">
                                        <input type="radio" class="form-control custom-control-input"
										id="customControlValidation1" name="status" value="1"
										@if ($work->status) checked  @endif required>
                                        <label class="custom-control-label" for="customControlValidation1">Active</label>
                                    </div>
                                     <div class="custom-control custom-radio">
                                        <input type="radio" class="form-control custom-control-input" id="customControlValidation2" name="status" value="0"
										@if (!$work->status) checked  @endif required>
                                        <label class="custom-control-label" for="customControlValidation2">Inactive</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3 text-right control-label col-form-label">File Upload</label>
                                <div class="col-md-9">
                                    <div class="custom-file">
                                        <input type="file" name="file" class="custom-file-input" id="validatedCustomFile">
                                        <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
                                        <div class="invalid-feedback">Example invalid custom file feedback</div>
                                    </div>
									@if(!empty($work->image))
                                    	<img class="img-rounded" src="{{ asset($work->image) }}"
									style="padding-top:  5px;max-width: 200px;">
									@endif
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <textarea name="description" class="form-control ckeditor" id="editor1">{!! $work->description !!}</textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-3 text-right control-label col-form-label">Start date</label>
                                <div class="input-group col-sm-9">
                                    <input type="text" name="start_date" class="form-control mydatepicker" value="{{ $work->start_date }}" placeholder="yyyy-mm-dd 00:00:00">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-3 text-right control-label col-form-label">End date</label>
                                <div class="input-group col-sm-9">
                                    <input type="text" name="end_date" class="form-control" id="datepicker-autoclose" value="{{ $work->end_date }}" placeholder="yyyy-mm-dd 00:00:00">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                                    </div>
                                </div>
                            </div>


                            {{-- <div class="form-group row">
                                <label class="col-sm-3 text-right control-label col-form-label">Test date</label>
                                <div class="input-group col-sm-9">
                                    <input type="date" name="test_date" class="form-control" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}">
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                                    </div>
                                </div>
                            </div> --}}


                        </div>
                        <div class="border-top">
                            <div class="card-body">
                                <a href="{{ route('work.index') }}" type="submit" class="btn btn-danger">Cancel</a>
                                <button type="submit" class="btn btn-primary">Update work</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('script')
    <script src="{{ asset('cms/ckeditor/ckeditor.js') }}"></script>
	<script src="{{ asset('cms/assets/libs/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/extra-libs/sparkline/sparkline.js') }}"></script>
    <script src="{{ asset('cms/dist/js/waves.js') }}"></script>
    <script src="{{ asset('cms/dist/js/sidebarmenu.js') }}"></script>
    <script src="{{ asset('cms/dist/js/custom.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>
    <script src="{{ asset('cms/dist/js/pages/mask/mask.init.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/select2/dist/js/select2.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asColor/dist/jquery-asColor.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asGradient/dist/jquery-asGradient.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asColorPicker/dist/jquery-asColorPicker.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-minicolors/jquery.minicolors.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        //***********************************//
        // For select 2
        //***********************************//
        $(".select2").select2();

        /*colorpicker*/
        $('.demo').each(function() {
        //
        // Dear reader, it's actually very easy to initialize MiniColors. For example:
        //
        //  $(selector).minicolors();
        //
        // The way I've done it below is just for the demo, so don't get confused
        // by it. Also, data- attributes aren't supported at this time...they're
        // only used for this demo.
        //
        $(this).minicolors({
                control: $(this).attr('data-control') || 'hue',
                position: $(this).attr('data-position') || 'bottom left',

                change: function(value, opacity) {
                    if (!value) return;
                    if (opacity) value += ', ' + opacity;
                    if (typeof console === 'object') {
                        console.log(value);
                    }
                },
                theme: 'bootstrap'
            });

        });
        /*datwpicker*/
        jQuery('.mydatepicker').datepicker();
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });

    </script>
@endsection