routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Client')->group(function () {
	Route::get('/', 'SiteController@home')->name('home');

	Route::get(
		'bautizo',
		'SiteController@christening'
	)->name('christening')->middleware('auth');

	Route::get(
		'view-cv',
		'CurriculumVitaeController@viewCurriculumVitae'
	)->name('view-cv');
	Route::get(
		'download-cv',
		'CurriculumVitaeController@downloadCurriculumVitae'
	)->name('download-cv');
	Route::get(
		'curriculum-vitae-carlos-amores',
		'CurriculumVitaeController@index'
	)->name('curriculum');

	Route::get('curriculum-{name}', function ($name) {
		return redirect(route('curriculum'), 301);
	})->where('name', '[A-Za-z]+');

	// Blog
	Route::group(['prefix' => 'blog'], function () {
		Route::get(
			'/',
			'MiniblogController@home'
		)->name('blog');
		// Route::get(
		//     '/{category}',
		//     'MiniblogController@category'
		// )->name('blog.category');
		Route::get(
			'/{title}',
			'MiniblogController@post'
		)->name('blog.post');
	});
});

// Authentication
Auth::routes();

Route::namespace('Admin')->group(function () {
	Route::prefix('admin')->group(function () {
		Route::group(['middleware' => 'auth'], function () {
			Route::get('/', 'AdminController@home')->name('cms-home');

			Route::resource('/encryption', 'EncryptionController');

			// CRUD with Vuejs
			Route::get('articles', function () {
				return view('back.article.index');
			})->name('articles.index');
			// List articles
			Route::get('article', 'ArticleController@index');
			// List single article
			Route::get('article/{id}', 'ArticleController@show');
			// Create new article
			Route::post('article', 'ArticleController@store');
			// Update article
			Route::put('article', 'ArticleController@store');
			// Delete article
			Route::delete('article/{id}', 'ArticleController@destroy');

			// Crud with MongoDB
			Route::resource('/car', 'CarController');

			// Edit and update user profile
			// Route::resource(
			//     '/user',
			//     'UserController',
			//     ['only' => ['edit', 'update']]
			// );
			Route::get(
				'/user/{user}/edit',
				'UserController@edit'
			)->name('user-edit');
			Route::put(
				'/user/{user}',
				'UserController@update'
			)->name('user-update');

			// Invoices Carlos Cueva
			Route::resource('/invoice', 'InvoiceController');
			Route::get(
				'/download-all-invoices-{month}',
				'InvoiceController@downloadAllInvoice'
			)->name('download-all-invoices');
			Route::post(
				'/sent-all-invoices-{month}',
				'InvoiceController@sentAllInvoice'
			)->name('sent-all-invoices');
			Route::get(
				'/invoice-pdf-{cif}-{year}-{month}/{number?}',
				'InvoiceController@downloadInvoice'
			)->name('download-invoice');
			Route::get(
				'/invoice-{cif}-{year}-{month}/{number?}',
				'InvoiceController@showInvoice'
			)->name('show-invoice');

			Route::group(['middleware' => 'superadmin'], function () {
				Route::resource('/work', 'WorkController');
				Route::resource('/skill', 'SkillController');
				Route::resource('/miniskill', 'MiniskillController');
			});
		});
	});
});

// Routes to SuperAdmin
Route::group(
	[
		'prefix' => 'super-admin',
		'namespace' => 'Admin',
		'middleware' => ['auth', 'superadmin'],
	],
	function () {
		Route::get('/', 'SuperAdminController@home')->name('super.admin.home');
		Route::resource(
			'/user',
			'UserController'
		);
		Route::resource('/notice', 'NoticeController');
		Route::resource('/amazon-product', 'AmazonProductController');
		Route::resource('/post', 'PostController');
		Route::get(
			'/houses/simulation',
			'HouseController@simulation'
		)->name('simulation');
		Route::resource('/houses', 'HouseController');
	}
);

app/Http/Controllers/Admin/UserController.php
<?php

namespace Carlos\Amores\Http\Controllers\Admin;

use Carlos\Amores\Http\Controllers\Controller;
use Carlos\Amores\Models\Role;
use Carlos\Amores\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

class UserController extends Controller
{
	public const PAGINATE = 500;
	/**
	 * Private variable.
	 *
	 * @var string
	 */
	private $publicPath;

	/**
	 * Create a new controller instance.
	 *
	 *
	 * @SuppressWarnings(PHPMD.ElseExpression)
	 */
	public function __construct()
	{
		if (App::environment(['local', 'staging'])) {
			$this->publicPath = 'public';
		} else {
			$this->publicPath = 'public_html';
		}
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$users = User::with('role')->paginate(self::PAGINATE);
		// return view('admin.user.index', compact('users'));
		return view('super-admin.user.index', compact('users'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('super-admin.user.create');
		// return view('admin.user.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$fields = $request->all();
		if ($request->has('editor1')) {
			$fields['description'] = $request->editor1;
			unset($fields['editor1']);
		}
		$fields['password'] = bcrypt($request->password);
		$fields['verified'] = User::USER_NOT_VERIFIED;
		$fields['verification_token'] = User::generateVerificationToken();
		$fields['admin'] = User::USER_REGULAR;
		$fields['role_id'] = Role::DEFAULT;
		$fields['password'] = bcrypt($request->password);
		$user = User::create($fields);
		$this->storeImgForUser($request, $user);
		$this->storeCurriculumVitae($request);

		return redirect()->route('user.index')
			->with('primary', 'User updated correctly');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param \Carlos\Amores\Models\User $user
	 *
	 * @return \Illuminate\Http\Response
	 *
	 * @SuppressWarnings(PHPMD.UnusedFormalParameter)
	 */
	public function show(User $user)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param \Carlos\Amores\Models\User $user
	 *
	 * @return \Illuminate\Http\Response
	 *
	 * @SuppressWarnings(PHPMD.ElseExpression)
	 */
	public function edit(User $user)
	{
		$authUser = Auth::user();
		if (!$authUser->isSuperadmin() && $authUser->id !== $user->id) {
			return redirect()->route('cms-home');
		}
		$roles = Role::all();
		if ($authUser->isSuperadmin()) {
			return view('super-admin.user.edit', compact('user', 'roles'));
		} else {
			return view('admin.user.edit', compact('user', 'roles'));
		}
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param \Illuminate\Http\Request   $request
	 * @param \Carlos\Amores\Models\User $user
	 *
	 * @return \Illuminate\Http\Response
	 *
	 * @SuppressWarnings(PHPMD.ElseExpression)
	 */
	public function update(Request $request, User $user)
	{
		$fields = $request->all();
		if ($request->has('editor1')) {
			$fields['description'] = $request->editor1;
			unset($fields['editor1']);
		}
		if (!empty($request->password)) {
			$fields['password'] = bcrypt($request->password);
		} else {
			unset($fields['password']);
		}
		if (!Auth::user()->isSuperadmin()) {
			unset($fields['role_id']);
		} else {
			$fields['role_id'] = (int) $request->role_id;
		}
		$user->update($fields);
		$this->storeImgForUser($request, $user);
		$this->storeCurriculumVitae($request);
		if ($user->isSuperadmin()) {
			Cache::forget('user');
		}

		return redirect()->back()->with('primary', 'User updated correctly');
	}

	/**
	 * Store img for user.
	 *
	 * @param Request $request
	 * @param User    $user
	 */
	private function storeImgForUser(Request $request, User $user)
	{
		if ($request->file('image')) {
			$nameImage = $user->full_name_slug . '.' .
				$request->file('image')->extension();
			$usersPath = base_path() . '/' . $this->publicPath . '/img/users/';
			$request->file('image')->move($usersPath, $nameImage);
			$user->image = 'img/users/' . $nameImage;
			$user->save();
		}
	}

	/**
	 * Undocumented function.
	 *
	 * @param Request $request
	 *
	 * @SuppressWarnings(PHPMD)
	 */
	private function storeImgForProduct(Request $request)
	{
		if ($request->file('file')) {
			$imageName = Str::slug($request->name) . '-'
			. Str::slug($request->lastname) . '.'
			. $request->file('file')->getClientOriginalExtension();
			if (env('APP_ENV') == 'local') {
				$request->file('file')
					->move(base_path() . '/public/img/', $imageName);
			} else {
				$request->file('file')
					->move(base_path() . '/public_html/img/', $imageName);
				//$request->file('file')
				//    ->move(base_path() . '/public/img/', $imageName);
			}
		}
	}

	/**
	 * Undocumented function.
	 *
	 * @param Request $request
	 *
	 * @SuppressWarnings(PHPMD.ElseExpression)
	 */
	private function storeCurriculumVitae(Request $request)
	{
		if ($request->file('cv')) {
			$imageName = 'cv-' . Str::slug($request->name) . '-'
			. Str::slug($request->lastname) . '.'
			. $request->file('cv')->getClientOriginalExtension();
			if (env('APP_ENV') == 'local') {
				$request->file('cv')
					->move(base_path() . '/public/', $imageName);
			} else {
				$request->file('cv')
					->move(base_path() . '/public_html/', $imageName);
			}
		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param \Carlos\Amores\Models\User $user
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(User $user)
	{
		$user->delete();

		return redirect()->route('user.index')
			->with('dark', 'User deleted successfully');
	}
}

app/Http/Controllers/Api/User/UserController.php
<?php

declare(strict_types=1);

namespace Carlos\Amores\Http\Controllers\Api\User;

use Carlos\Amores\Http\Controllers\ApiController;
use Carlos\Amores\Lib\Constants\HttpStatusCodes;
use Carlos\Amores\Mail\UserCreatedMail;
use Carlos\Amores\Models\Role;
use Carlos\Amores\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

// Anotations
// https://github.com/DarkaOnLine/L5-Swagger/blob/master/tests/storage/annotations/OpenApi/Anotations.php

/**
 * @OA\Info(
 *      version="1.0.0",
 *      title="API Doc",
 *      description="API Doc Description",
 *      @OA\Contact(
 *          email="amorescarlos93@hotmail.com"
 *      )
 * )
 */

/**
 *  @OA\Server(
 *      url=L5_SWAGGER_CONST_HOST,
 *      description="API Doc"
 *  )
 */
class UserController extends ApiController
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */

	/**
	 * @OA\Get(
	 *     tags={"Users"},
	 *     path="/api/users",
	 *     summary="Show users",
	 *     description="List all users",
	 *     @OA\Response(
	 *         response=200,
	 *         description="Show all users"
	 *     ),
	 *     @OA\Response(
	 *         response="default",
	 *         description="Ha ocurrido un error."
	 *     )
	 * )
	 */
	public function index()
	{
		// $users = User::all();
		$users = User::forNotSuperAdmin()->get();

		return $this->showAll($users);
		// return response()->json(['data' => $users], 200);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$request->validate([
			'name' => 'required',
			'email' => 'required|email|unique:users',
			'password' => 'required|min:5',
		]);
		$fields = $request->all();
		$fields['password'] = bcrypt($request->password);
		$fields['verified'] = User::USER_NOT_VERIFIED;
		$fields['verification_token'] = User::generateVerificationToken();
		$fields['admin'] = User::USER_REGULAR;
		$fields['role_id'] = Role::DEFAULT;
		$user = User::create($fields);

		return $this->showOne($user);
		// return response()->json(['data' => $user], HttpStatusCodes::CREATED);
	}

	/**
	 * @OA\Get(
	 *      path="/api/users/{userId}",
	 *      operationId="getUserById",
	 *      tags={"Users"},
	 *      summary="Get user information",
	 *      description="Returns user data",
	 *      @OA\Parameter(
	 *          name="userId",
	 *          description="User id",
	 *          required=true,
	 *          in="path",
	 *          @OA\Schema(
	 *              type="integer"
	 *          )
	 *      ),
	 *      @OA\Response(
	 *          response=200,
	 *          description="successful operation"
	 *       ),
	 *      @OA\Response(response=400, description="Bad request"),
	 *      @OA\Response(response=404, description="Resource Not Found"),
	 * )
	 */

	/**
	 * Display the specified resource.
	 *
	 * @param User $user
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show(User $user)
	{
		// $user = User::findOrFail($id);
		if ($user->isSuperadmin()) {
			return $this->errorResponse(
				'No se puede ver al usuario al superadmin',
				HttpStatusCodes::CONFLICT
			);
		}

		return $this->showOne($user);
		// return response()->json(['data' => $user], 200);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Http\Response
	 *
	 * @SuppressWarnings(PHPMD.UnusedFormalParameter)
	 */
	public function edit($id)
	{
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @param User                     $user
	 *
	 * @return \Illuminate\Http\Response
	 *
	 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
	 * @SuppressWarnings(PHPMD.NPathComplexity)
	 */
	public function update(Request $request, User $user)
	{
		if ($user->isSuperadmin()) {
			return $this->errorResponse(
				'No se puede editar al superadmin',
				HttpStatusCodes::CONFLICT
			);
		}
		// $user = User::findOrFail($id);
		$rules = [
			'email' => 'email|unique:users,email,' . $user->id,
			'password' => 'min:5',
			'admin' => 'in:' . User::USER_REGULAR . ',' . User::USER_ADMIN,
		];

		$this->validate($request, $rules);

		if ($request->has('name')) {
			$user->name = $request->name;
		}

		if ($request->has('role_id')) {
			$user->role_id = Role::DEFAULT;
		}

		if ($request->has('email') && $user->email !== $request->email) {
			$user->verified = User::USER_NOT_VERIFIED;
			$user->verification_token = User::generateVerificationToken();
			$user->email = $request->email;
		}

		if ($request->has('password')) {
			$user->password = bcrypt($request->password);
		}

		if ($request->has('admin')) {
			if (!$user->isVerified()) {
				return $this->errorResponse(
					'Únicamente los usuarios verificados pueden cambiar su valor de administrador',
					HttpStatusCodes::CONFLICT
				);
				// return response()->json(
				//     [
				//         'error' => 'Únicamente los usuarios verificados pueden cambiar su valor de administrador',
				//         'code' => HttpStatusCodes::CONFLICT
				//     ],
				//     HttpStatusCodes::CONFLICT
				// );
			}
			$user->admin = $request->admin;
		}

		if (!$user->isDirty()) {
			return $this->errorResponse(
				'Se debe especificar al menos un valor diferente para actualizar',
				HttpStatusCodes::UNPROCESSABLE_ENTITY
			);
			// return response()->json([
			//     'error' => 'Se debe especificar al menos un valor diferente para actualizar',
			//     'code' => HttpStatusCodes::UNPROCESSABLE_ENTITY
			// ], HttpStatusCodes::UNPROCESSABLE_ENTITY);
		}

		$user->save();

		return $this->showOne($user);
		// return response()->json(['data' => $user], 200);
	}

	/**
	 * @OA\Delete(
	 *     path="/api/users/{userId}",
	 *     summary="Deletes a user",
	 *     description="",
	 *     operationId="deleteUser",
	 *     tags={"Users"},
	 *     @OA\Parameter(
	 *         description="User id to delete",
	 *         in="path",
	 *         name="userId",
	 *         required=true,
	 *         @OA\Schema(
	 *             type="integer",
	 *             format="int64"
	 *         )
	 *     ),
	 *     @OA\Response(
	 *          response=200,
	 *          description="successful operation"
	 *       ),
	 *     @OA\Response(
	 *         response=400,
	 *         description="Invalid ID supplied"
	 *     ),
	 *     @OA\Response(
	 *         response=404,
	 *         description="User not found"
	 *     )
	 * )
	 */

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param User $user
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(User $user)
	{
		if ($user->isSuperadmin()) {
			return $this->errorResponse(
				'No se puede elimminar al superadmin',
				HttpStatusCodes::CONFLICT
			);
		}
		// $user = User::findOrFail($id);
		$user->delete();

		return $this->showOne($user);
		// return response()->json(['data' => $user], 200);
	}

	/**
	 * Verify.
	 *
	 * @param string $token
	 *
	 * @return JsonResponse
	 */
	public function verify(string $token)
	{
		$user = User::forVerificationToken($token)->firstOrFail();
		$user->verified = User::USER_VERIFIED;
		$user->verification_token = null;
		$user->email_verified_at = now();
		$user->save();

		return $this->showMessage('La cuenta ha sido verificada');
	}

	/**
	 * Verify.
	 *
	 * @param User $user
	 *
	 * @return JsonResponse
	 */
	public function resend(User $user)
	{
		if ($user->isVerified()) {
			return $this->errorResponse('El usuario ya ha sido verificado', HttpStatusCodes::CONFLICT);
		}
		Mail::to($user)->send(new UserCreatedMail($user));

		return $this->showMessage('El correo electrónico se ha reenviado');
	}
}

resources/views/admin/user/create.blade.php
@extends('templates.admin.layout')

@section('head')
	<title>Create user</title>
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/jquery-minicolors/jquery.minicolors.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('cms/assets/libs/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <link href="{{ asset('cms/dist/css/style.min.css') }}" rel="stylesheet">
@endsection


@section('content')
	<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <form method="POST" class="form-horizontal"
                        action="{{ route('user.store') }}" enctype="multipart/form-data">
                        @csrf
                        @method('POST')
                        <div class="card-body">
                            <h2 class="card-title">Create user</h2>
                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Name</label>
                                <div class="col-sm-9">
                                    <input type="text" name='name' class="form-control" id="email1" placeholder="Name" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Lastname</label>
                                <div class="col-sm-9">
                                    <input type="text" name='lastname' class="form-control" id="email1" placeholder="Lastname">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Email</label>
                                <div class="col-sm-9">
                                    <input type="email" name='email' class="form-control" id="email1" placeholder="Email" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Username</label>
                                <div class="col-sm-9">
                                    <input type="username" name='username' class="form-control"
                                    id="email1" placeholder="Username">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Phone</label>
                                <div class="col-sm-9">
                                    <input type="number" name='phone'
                                    class="form-control" id="email1" placeholder="Phone"
                                    required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1"
                                class="col-sm-3 text-right control-label col-form-label">Password</label>
                                <div class="col-sm-9">
                                    <input type="text" name='password'
                                    class="form-control" id="email1" placeholder="Password"
                                    required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Career</label>
                                <div class="col-sm-9">
                                    <input type="text" name='career' class="form-control" id="email1" placeholder="Career">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Profession</label>
                                <div class="col-sm-9">
                                    <input type="text" name='profession' class="form-control" id="email1" placeholder="Profession">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">University</label>
                                <div class="col-sm-9">
                                    <input type="text" name='university' class="form-control" id="email1" placeholder="University">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Faculty</label>
                                <div class="col-sm-9">
                                    <input type="text" name='faculty' class="form-control" id="email1" placeholder="Faculty">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Address</label>
                                <div class="col-sm-9">
                                    <input type="text" name='address' class="form-control" id="email1" placeholder="Address">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Github</label>
                                <div class="col-sm-9">
                                    <input type="text" name='github' class="form-control" id="email1" placeholder="Github">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Gitlab</label>
                                <div class="col-sm-9">
                                    <input type="text" name='gitlab' class="form-control" id="email1" placeholder="Gitlab">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Linkedin</label>
                                <div class="col-sm-9">
                                    <input type="text" name='linkedin' class="form-control" id="email1" placeholder="Linkedin">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email1" class="col-sm-3 text-right control-label col-form-label">Website</label>
                                <div class="col-sm-9">
                                    <input type="text" name='website' class="form-control" id="email1" placeholder="Website">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-3 text-right control-label col-form-label">Photo</label>
                                <div class="col-md-9">
                                    <div class="custom-file">
                                        <input type="file" name="image" class="custom-file-input" id="validatedCustomFile">
                                        <label class="custom-file-label" for="validatedCustomFile">Choose photo user...</label>
                                        <div class="invalid-feedback">Example invalid custom file feedback</div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-3 text-right control-label col-form-label">CV</label>
                                <div class="col-md-9">
                                    <div class="custom-file">
                                        <input type="file" name="cv" class="custom-file-input" id="validatedCustomFile">
                                        <label class="custom-file-label" for="validatedCustomFile">Choose cv...</label>
                                        <div class="invalid-feedback">Example invalid custom file feedback</div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Description</label>
                                <div class="col-sm-9">
                                    <textarea name="description" class="form-control ckeditor" id="editor1"></textarea>
                                </div>
                            </div>

                        </div>
                        <div class="border-top">
                            <div class="card-body">
                                <a href="{{ route('user.index') }}" type="submit" class="btn btn-danger">Users</a>
                                <button type="submit" class="btn btn-primary">Store user</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('script')
    <script src="{{ asset('cms/ckeditor/ckeditor.js') }}"></script>
	<script src="{{ asset('cms/assets/libs/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ asset('cms/assets/extra-libs/sparkline/sparkline.js') }}"></script>
    <script src="{{ asset('cms/dist/js/waves.js') }}"></script>
    <script src="{{ asset('cms/dist/js/sidebarmenu.js') }}"></script>
    <script src="{{ asset('cms/dist/js/custom.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>
    <script src="{{ asset('cms/dist/js/pages/mask/mask.init.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/select2/dist/js/select2.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asColor/dist/jquery-asColor.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asGradient/dist/jquery-asGradient.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-asColorPicker/dist/jquery-asColorPicker.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/jquery-minicolors/jquery.minicolors.min.js') }}"></script>
    <script src="{{ asset('cms/assets/libs/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        //***********************************//
        // For select 2
        //***********************************//
        $(".select2").select2();

        /*colorpicker*/
        $('.demo').each(function() {
        //
        // Dear reader, it's actually very easy to initialize MiniColors. For example:
        //
        //  $(selector).minicolors();
        //
        // The way I've done it below is just for the demo, so don't get confused
        // by it. Also, data- attributes aren't supported at this time...they're
        // only used for this demo.
        //
        $(this).minicolors({
                control: $(this).attr('data-control') || 'hue',
                position: $(this).attr('data-position') || 'bottom left',

                change: function(value, opacity) {
                    if (!value) return;
                    if (opacity) value += ', ' + opacity;
                    if (typeof console === 'object') {
                        console.log(value);
                    }
                },
                theme: 'bootstrap'
            });

        });
        /*datwpicker*/
        jQuery('.mydatepicker').datepicker();
        jQuery('#datepicker-autoclose').datepicker({
            autoclose: true,
            todayHighlight: true
        });

    </script>
@endsection